print("My name is krish")
print("My name is krish") 
print("My name is krish") 
print("My name is krish") 
print("My name is krish") 
print("My name is krish") 
print("My name is krish") 
print("My name is krish") 